### ISSUE TITLE
Problem with alpha canal

### ISSUE THREAD

**Issue by veolys-nanne** [Exercise/HTMLPurifierBundle#103]
With the following configuration:
```
exercise_html_purifier:
    default:
        HTML.Allowed: '*[id|class|name|style|alt|title|height|width],a[href|rel|target],img[src],br,div,u,em,ul,ol,li,strong,span,p,i'
        HTML.SafeIframe: true
        URI.SafeIframeRegexp: '#(.*)#'
        URI.AllowedSchemes: ['data', 'http', 'https', 'mailto', 'tel']
```
If I purify ```<span style="color:#FF0000;>test</span>```, the result is ```<span style="color:#FF0000;>test</span>```.
If I purify ```<span style="color:#FF0000FF;>test</span>```, the result is ```<span>test</span>```.
It seems that alpha canal is not accepted?
