### ISSUE TITLE
Configuration of htmlpurifier in Symfony 3.4

### ISSUE THREAD

**Issue by greenkey-m** [Exercise/HTMLPurifierBundle#73]
I tried to remove cache_serializer_path from symfony cache folder to another (tmp), as it described in readme, but its not work.
As i understood, it must be something like this (config.yml):

```
exercise_html_purifier:
    default_cache_serializer_path: null
    custom:
        Cache.SerializerPath: 'tmp/htmlpurifier'
```

and i call this service as: $this->kernel->getContainer()->get('exercise_html_purifier.custom')

In this case, folder not removed to /tmp path, but htmlpurifier restore folder in symfony cache ;-)

And, i tried another ways, like these:
```
exercise_html_purifier:
    default_cache_serializer_path: null
    html_profiles:
        custom:
            config:
                Cache.SerializerPath: 'tmp/htmlpurifier'

```
or 

```
exercise_html_purifier:
    default_cache_serializer_path: null
    html_profiles:
        custom:
            Cache.SerializerPath: 'tmp/htmlpurifier'

```
And this is not work at all.

**Comment by HeahDude** [comment]
Hello @greenkey-m, thanks for the report. Which version are you currently using? 2.0 or 3.0-beta?

**Comment by greenkey-m** [comment]
I am using version 2.0.5

**Comment by HeahDude** [comment]
I could not reproduce the issue. When using version 2.0, be sure you're reading the 2.0 branch of the README.
The correct config should be:
```yaml
exercise_html_purifier:
    default:
        Cache.SerializerPath: null
    custom:
        Cache.SerializerPath: 'tmp/htmlpurifier'
```
I'm closing here though, don't hesitate to reopen if this does not fix your issue. Thanks
