### ISSUE TITLE
The option "purify_html" does not exist

### ISSUE THREAD

**Issue by coderste** [Exercise/HTMLPurifierBundle#84]
Trying to add the `purify_html` option to my forms text type and currently getting this error:

```
An error has occurred resolving the options of the form "Symfony\Component\Form\Extension\Core\Type\TextType": The option "purify_html" does not exist. Defined options are: "action", "allow_extra_fields", "allow_file_upload", "attr", "attr_translation_parameters", "auto_initialize", "block_name", "block_prefix", "by_reference", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "help", "help_attr", "help_html", "help_translation_parameters", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "label_translation_parameters", "mapped", "method", "post_max_size_message", "property_path", "required", "row_attr", "translation_domain", "trim", "upload_max_size_message", "validation_groups".
```

- Symfony Version: 4.4.2
- Is Symfony using flex? Nope

I have the bundle registered inside `config/bundles.php` and the below inside my `services.yml`
```
# config/services.yml
    Exercise\HtmlPurifierBundle\HtmlPurifiersRegistry:
        tags:
            - name: exercise.html_purifier
              profile: default
```
