### ISSUE TITLE
Combining "rel=" properties with URI.Munge

### ISSUE THREAD

**Issue by Soonz** [Exercise/HTMLPurifierBundle#90]
Hello,

I want to use URI.Munge but with the nofollow property and it doesn't work.

```yaml
URI.Munge: '/redirect?url=%s' 
HTML.Nofollow: true 
HTML.TargetBlank: true 
HTML.TargetNoopener: true 
HTML.TargetNoreferrer: true 
```

Is it possible or it needs an update ?

Thanks.
