### ISSUE TITLE
Cache permission issue since 4.1

### ISSUE THREAD

**Issue by dmaicher** [Exercise/HTMLPurifierBundle#95]
It seems https://github.com/Exercise/HTMLPurifierBundle/commit/9712ab74579222d58f5e20a12afe8ff0648b0ed3 is causing some issues for one of my apps.

I have this config:

```yaml
exercise_html_purifier:
    html_profiles:
        default:
            config:
                Cache.SerializerPermissions: 0o777
```

Using 4.1 however my config is overwritten by the new default config it seems.
